### ISSUE TITLE
google chrome 浏览器   运行结果: ip定位(不精准):"ip定位失败"    h5定位:"html5定位超时"

### ISSUE THREAD

**Issue by lovemory** [pikaz-18/pikaz-location#1]
google chrome 浏览器 
运行结果:
ip定位(不精准):"ip定位失败"

h5定位:"html5定位超时"

edge  浏览器：
运行结果:
ip定位(不精准):"ip定位失败"

h5定位:{"province":"广东省","city":"深圳市","district":"福田区","code":"440304","details":{"province":{"code":"440000","location":{"latitude":23.13171,"longitude":113.26627},"name":"广东省","pinyin":"guangdong"},"city":{"code":"440300","location":{"latitude":22.54286,"longitude":114.05956},"name":"深圳市","pinyin":"shenzhen"},"district":{"code":"440304","location":{"latitude":22.521541,"longitude":114.05498},"name":"福田区","pinyin":"futianqu"}},"latitude":22.5436,"longitude":114.0579}

**Comment by pikaz-18** [comment]
> google chrome 浏览器 运行结果: ip定位(不精准):"ip定位失败"
> 
> h5定位:"html5定位超时"
> 
> edge 浏览器： 运行结果: ip定位(不精准):"ip定位失败"
> 
> h5定位:{"province":"广东省","city":"深圳市","district":"福田区","code":"440304","details":{"province":{"code":"440000","location":{"latitude":23.13171,"longitude":113.26627},"name":"广东省","pinyin":"guangdong"},"city":{"code":"440300","location":{"latitude":22.54286,"longitude":114.05956},"name":"深圳市","pinyin":"shenzhen"},"district":{"code":"440304","location":{"latitude":22.521541,"longitude":114.05498},"name":"福田区","pinyin":"futianqu"}},"latitude":22.5436,"longitude":114.0579}

已更新新版本，更改了定位文件请求策略，优化了定位速度，新增多个工具函数，请升级到最新版本体验
