### ISSUE TITLE
在使用【searchList】时传code参数，返回为[]

### ISSUE THREAD

**Issue by puxiaoruo** [pikaz-18/pikaz-location#3]
// 省市区三级联动，传入对应行政单位编码，获取下级行政单位列表；不传行政单位编码默认获取省级单位列表
  const toSearchList = async () => {
    const result = await searchList({code: "410000"})
    console.log('toSearchList result :>> ', result); // []
  }

**Comment by pikaz-18** [comment]
> // 省市区三级联动，传入对应行政单位编码，获取下级行政单位列表；不传行政单位编码默认获取省级单位列表 const toSearchList = async () => { const result = await searchList({code: "410000"}) console.log('toSearchList result :>> ', result); // [] }

写示例时对着代码写的，看着示例跑通了，忘了和文档做校对了orz；现已修复，安装最新npm包版本即可，感谢使用
